jwt:
  access-token:
    expire-time: ${SECRET-KEY:10000}
  refresh-token:
    expire-time: ${REFRESH-EXPIRE-TIME:10000}
  secret-key: ${SECRET-KEY:SECRET-KEY}

oauth2:
  user:
    google:
      client-id: 1089824765759-q2bgds4v0ib9tcf6771n0qiafp69tjkv.apps.googleusercontent.com
      client-secret: ${CLIENT-SECRET:EMPTY}
      redirect-uri: http://localhost:8080/oauth/callback/google
      scope: email
  provider:
    google:
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?client_id=%s&redirect_uri=%s&response_type=code&scope=%s